# Site settings
title: Hieu's Blog
description: "Writing is not my hobby, but a need for my future study."
url: "https://tthieuhcm.github.io"
author:
  name: "Hieu Tran-Trung"
  email: "tthieuhcm@gmail.com"
  url: "https://tthieuhcm.github.io"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./docs
# permalink: /index.html
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
